version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requierments.txt
      - run:
          name: Run Tests
          command: pytest